### ISSUE TITLE
Engage the disease ontology to correct that prostate cancer is a cancer located in the prostate.

### ISSUE THREAD

**Issue by andredekker** [aapm-bdsc-ontology-tg/radont#1]

**Comment by jonathanbona** [comment]
A related (closed) issue in the DO tracker: https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/649

**Comment by jonathanbona** [comment]
The specific issue I remember this discussing was pancreatic adenocarcinoma. 
In DO, currently ['pancreatic adenocarcinoma' subclassof (cancer and ('located in' some pancreas)].

**Comment by andredekker** [comment]
this is a duplicate issue #12 , closing
