### ISSUE TITLE
Follow up with Disease Ontology on 'pancreatic adenocarcinoma' located_in some pancreas

### ISSUE THREAD

**Issue by jonathanbona** [aapm-bdsc-ontology-tg/radont#12]

**Comment by jonathanbona** [comment]
https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/829

**Comment by jonathanbona** [comment]
https://github.com/DiseaseOntology/HumanDiseaseOntology/issues/829

**Comment by andredekker** [comment]
I have again argued with DO that this is wrong. Nonetheless I imported prostate cancer from DO into radont. It has multiple parents so we should see if we like that.

**Comment by andredekker** [comment]
For one of the coming meetings, I would like to discuss the followin
1. What (if any) disease do we import from the Disease Ontology -> my suggestion is to include all cancers
2. What axioms do we import from the Disease Ontology -> my suggestion is to only include the subClassOf hierarchy and labels etc. but no other axioms (so also not the located_in)
3. On the matter of :prostate_cancer :located_in some :prostate can we accept this and state that this is - at some point in time - a true statement. It may not be true now (just has a cured breast cancer patient is not a cancer patient anymore) but it is true that at some point in time a person who played the patient role and had (primary or metastatic) prostate cancer, had cancer cells which were located in the prostate? That way we can simply accept the DO's position and move on.

**Comment by Bayesianworld** [comment]
Hi Andre,
All good points--thanks for pursuing this.  If those problems don't seem enough, perhaps you can try to figure out the somewhat common "unknown primary" which ends up in our diagnoses pretty often.

Andre said that he can't make the call tomorrow--how about everyone else?  I will be in my basement since it is the only cool place in the house.
Mark
________________________________

**Comment by andredekker** [comment]
DOID changed it to "disease has location" instead of "located in", but that is still not to our liking. We decided to not import these axioms of DOID just the entities and hierarchy....
