### ISSUE TITLE
Reuse or define radiation particles

### ISSUE THREAD

**Issue by andredekker** [aapm-bdsc-ontology-tg/radont#13]
For new term requests, please provide the following information:

## Preferred term label

(e.g., Asplenia)

## Synonyms

(e.g., Absent spleen)

## Textual definition

the definition should be understandable even for non-specialists. Include a PubMed ID to refer to any relevant article that provides additional information about the suggested term.

## Suggested parent term

Please look in the hierarchy in a browser such as [OLS](http://www.ebi.ac.uk/ols/ontologies/radont)

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

**Comment by andredekker** [comment]
Ontofoxed alpha, electron, photon, positron, proton, neutron from Chebi and subatomic particle as the superclass.

The following particles/ions cannot be found in Chebi 
3He (1+)
12C (4+) 
16O (6+)

**Comment by andredekker** [comment]
What axions to take from Chebi - i have now included all

**Comment by jonathanbona** [comment]
https://github.com/ebi-chebi/ChEBI/issues

**Comment by andredekker** [comment]
Make two issues on Chebi

1. Ask Chebi to add ions
2. Ask them about the particle superclass

**Comment by andredekker** [comment]
Submitted https://github.com/ebi-chebi/ChEBI/issues/3776 and https://github.com/ebi-chebi/ChEBI/issues/3775 as issues to ChEBI

**Comment by andredekker** [comment]
Particle superclass: no go with good reason, see https://github.com/ebi-chebi/ChEBI/issues/3776

**Comment by andredekker** [comment]
They added the missing three ions:
oxygen-16(6+) - CHEBI:149692
helium-3(1+) - CHEBI:149675
carbon-12(4+) - CHEBI:149691

**Comment by andredekker** [comment]
Added these terms to radont. closing
