### ISSUE TITLE
Establish simple process for adding new imported terms/ontologies

### ISSUE THREAD

**Issue by jonathanbona** [aapm-bdsc-ontology-tg/radont#16]
Right now when I want to add a term from another ontology to radont.owl, the process is as follows:

* Add the URI and optionally its label to a csv file, 'radont-import-terms.csv', for example

`http://purl.obolibrary.org/obo/OGMS_0000116,radiation therapy procedure
http://purl.obolibrary.org/obo/OBI_0000968,device
http://purl.obolibrary.org/obo/OBI_0000011,planned process
http://purl.obolibrary.org/obo/OBI_0000374,excitation function`

* Run a python script that slices up this file and calls Ontofox to generate separate import modules, one per ontology that appears in radont-import-terms:

`> ls imports`
`OBI-of-input.txt.owl	OGMS-of-input.txt.owl`

* Run a bash script that uses the OBO Robot tool to create a single merged import file 

`> ls imports/merged`
`merged-imports.owl`

* Finally, run a bash script that merges the merged-imports file with radont.owl

This sounds like a lot of steps but can all be combined into a single script. The advantage to this over the click & drag individual term import in Protege is that it is easily repeatable.

Is this workable? I'm happy to be the guy who runs the term import process when a refresh is occasionally needed, but I don't want to set us up with something only I am willing to use (I may get hit by a bus!)

**Comment by andredekker** [comment]
This reads  like a workable process – would like try it out for some chebi terms, can you put the scripts into the repo so that I can try it out?

**Comment by andredekker** [comment]
@jonathanbona : I am not sure you ever added this python script to the repo? 

@jonathanbona: I would also propose the following as part of the "import policy":
0. Select the ontology that has properly put the term you need in BFO (it happens regularly that the ontology that defined the concept and the ontology that imported it and put it into BFO are different, select the latter)
1. Select the term you need as the  low level source term URIs in Ontofox
2. Select the first BFO parent as the top level source term URI in Ontofox
3. Set includeAllIntermediates
4. Include the following annotations
http://www.w3.org/2000/01/rdf-schema#label
http://purl.obolibrary.org/obo/IAO_0000115

@jonathanbona : I would also propose the following as part of the "import policy"
We will import all entities we need in our domain into the radont ontology, provided that they follow BFO. We want to end up in a situation where to map data in our domain, you only need to have the radont ontology.
Any other entity, i.e. one not following BFO, should be placed in an application ontology.
radont does not import all axioms, i.e. if one want to do full inferencing you need to import the source ontologies.

**Comment by andredekker** [comment]
The above import policy is agreed for now. Tooling will be shared for this.
