### ISSUE TITLE
Homo sapiens

### ISSUE THREAD

**Issue by jonathanbona** [aapm-bdsc-ontology-tg/radont#29]
For convenience and posterity, I'm moving discussion of separate points from Mark's March 4 email titled 'AAPM abstract' into github issues.

Mark asks:
> On your graffle plot from some time ago, you use NCBIT:Homo sapiens with "patient" role.  Looking at NCBIT, to use this class, there are about 20 parent classes.  Do we have to include them all?  They also don't seem to follow the BFO ontology.

**Comment by jonathanbona** [comment]
I vote that we use only _NCIT: Homo sapiens_ and assert that it is a subclass of _BFO:material entity_.

**Comment by Bayesianworld** [comment]
It would be nice to use an ontology that has some demographic classes, e.g. birthdate, gender.  Even things like patient name and MRN?

**Comment by andredekker** [comment]
The most often used Homo Sapiens is from NCBIT not NCIT. But NCIT also has homo sapiens defined. @jonathanbona: In the above comment, do you indeed suggest using the NCIT or is this a typo and do you vote for using the NCBIT one?

**Comment by andredekker** [comment]
Homo sapiens defined in NCBIT but other ontologies have put it in its right place as a material entity, e.g. OBI. Should we import from there? At the moment it is not properly imported into radont.

**Comment by jonathanbona** [comment]
Yes. http://purl.obolibrary.org/obo/NCBITaxon_9606

Almost nothing is at the moment property imported into radont.

**Comment by andredekker** [comment]
@jonathanbona: I am correcting the imports. One question that i have: I use protege's Merge Ontologies function to merge the Ontofox exported (fraction of the) ontology into radont. This looks to go ok - but perhaps you do it differently?

**Comment by andredekker** [comment]
I imported homo sapiens.
