### ISSUE TITLE
CHeBI terms

### ISSUE THREAD

**Issue by jonathanbona** [aapm-bdsc-ontology-tg/radont#30]
For convenience and posterity, I'm moving discussion of separate points from Mark's March 4 email titled 'AAPM abstract' into github issues.

Mark asks:
> At some point, looks like someone included the Ontology of Chemical Elements to define subatomic particles.  However, I see that they have child classes that have two different parents.  I thought that was something we were trying to avoid.

**Comment by jonathanbona** [comment]
I propose we use these CHeBI terms and just ignore the multiple inheritance. It should cause minimal or no issues with reasoning in this case. 

An alternative is to come up with our own terms for those entities, but then we lose semantic interoperability with the other OBO and OBO-style ontologies using these term.

**Comment by andredekker** [comment]
Corrected the import - closing this issue
