### ISSUE TITLE
Given name, Family name

### ISSUE THREAD

**Issue by andredekker** [aapm-bdsc-ontology-tg/radont#34]
Will we choose OPMI or PNO for the name. Suggestion: OPMI

OPMI has defined person first name and person last name (and more extensive things like maiden name, middle name etc). 
The tree is   
- generically dependent continuant
- information content entity
- **textual entity**
- person name
- person first name

PNO can apparently use the IAO namespace (?) has defined a personal name IAO_0020015 (which does not resolve btw) in the tree
generically dependent continuant
information content entity
**identifier**
personal name
-given name
- family name

**Comment by andredekker** [comment]
@jonathanbona : What property do i use to give someone a certain name? And which one to set a value? 
Typically it would be something like below, but what do i use for ?1 and ?2
<andre> a homo sapiens
<andre> ?1 <name>
<name> a givenname
<name> ?2 "andre"

**Comment by jonathanbona** [comment]
Two issues with OMPI:
- A name is not a textual entity 
- 'First name' and 'last name' are culturally specific and lead to confusion when dealing with names of people whose convention is to specify the family name before the given name.

I would use 'denotes'  http://purl.obolibrary.org/obo/IAO_0000219 to connect the name to the person.

**Comment by andredekker** [comment]
imported PNO concepts into radont

**Comment by andredekker** [comment]
@jonathanbona: I was looking at [https://ddooley.github.io/assets/images/docs/data_john_bmi_context.png](url)  
Is the following the most logical/common way to set literals?

<name> IAO:denotes  <andre>
<name> a PNO:GivenName
<name_value> OBI:specifies_value_of <name>
<name_value> OBI:has_specified_value "andre"xsd:string

<andre> has_quality <length>
<length> a length
<length_value> OBI:specifies_value_of <length>
<length_value> OBI:has_specified_value "180"xsd:decimal
<length_value> OBI:has_measurement_unit_label UO:cm -> note that UO has punned its classes so i guess we can use that to our advantage

**Comment by andredekker** [comment]
![image](https://user-images.githubusercontent.com/2337314/121851091-00a49180-ccee-11eb-9a01-aaf680517cc5.png)

**Comment by andredekker** [comment]
I was reading a further discussion on this at the OBI forum which ended in this issue (https://github.com/obi-ontology/obi/pull/1040). Basically the above value specification should be limited to actual values and not to things like free text strings like names and like "30g" which may contain values but are not specified as such. These strings (but this could be broader than strings i think) should be represented with the has representation property http://purl.obolibrary.org/obo/OBI_0002815.

so
<name> IAO:denotes  <andre>
<name> a PNO:GivenName
<name> OBI:has_representation "andre"xsd:string

<andre> has_quality <length>
<length> a length
<length> OBI:has_representation "180cm"xsd:string
<length_value> a OBI: value specification
<length_value> OBI:specifies_value_of <length>
<length_value> OBI:has_specified_value "180"xsd:decimal
<length_value> OBI:has_measurement_unit_label UO:cm -> note that UO has punned its classes so i guess we can use that to our advantage

**Comment by andredekker** [comment]
Accept the above as the ok
