### ISSUE TITLE
'Patient'

### ISSUE THREAD

**Issue by jonathanbona** [aapm-bdsc-ontology-tg/radont#5]
The standard approach to representing a patient is to have an instance of 'Homo sapiens', and say that they are the bearer of a 'patient role' [1]. We may also want to then say that this patient role is realized by a process that the person participates in, such as a treatment they are undergoing. 

[1] http://purl.obolibrary.org/obo/OBI_0000093

**Comment by Bayesianworld** [comment]
That sounds good.  I like that approach.

**Comment by andredekker** [comment]
agree

**Comment by andredekker** [comment]
this is included in the ontology now.
